node.name = emqx@127.0.0.1
node.cookie = emqxsecretcookie

listener.tcp.external = 0.0.0.0:1883
listener.ws.external = 0.0.0.0:8083

allow_anonymous = false
acl_nomatch = deny

auth.http.auth_req.url = http://server:4000/api/mqtt/auth
auth.http.auth_req.method = post
auth.http.auth_req.params = clientid=%c,username=%u,password=%P
auth.http.auth_req.headers.x-emqx-secret = EMQX_SECRET_PLACEHOLDER

auth.http.acl_req.url = http://server:4000/api/mqtt/acl
auth.http.acl_req.method = post
auth.http.acl_req.params = access=%A,username=%u,clientid=%c,ipaddr=%a,topic=%t

dashboard.listener = 18083
